version: '3.3'
volumes:
  postgres_data: {}
  bundle_cache: {}
  app-gems:
  redis: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        - env=development
        - bundle_opts=
    depends_on:
      - box
      - db
      - redis
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
    ports:
      - "5000"
    env_file:
     - ./.env
    environment:
      - BUNDLE_PATH=/bundle_cache
      - REDIS_URL=redis://redis:6379/0/cache
      - RAILS_ENV=development
    restart: always

  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - /var/lib/postgresql/pgdata:/var/lib/postgresql/pgdata
    ports:
      - 5032:5432

  box:
    image: busybox
    tty: true
    volumes:
      - bundle_cache:/bundle_cache

  redis:
    image: 'redis:4.0-alpine'
    # command: redis-server --requirepass akileebox
    command: redis-server
    volumes:
    - redis:/app


