version: '3.2'
volumes:
  postgres_data: {}
  bundle_cache: {}
  app-gems:
  redis: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      
    # command: ./docker/script/bundle-install.sh
    # command: ./docker/script/bundle-install.sh 
    # entrypoint: ./docker-entrypoint.sh
    depends_on:
      - db
      - box
      - redis
    volumes:
      - .:/dd-authentification-api
      - bundle_cache:/bundle_cache
    ports:
      - 3001:3000
    env_file:
     - ./.env
    environment:
      - BUNDLE_PATH=/bundle_cache
      - REDIS_URL=redis://redis:6379/0/cache

  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 15432:5432
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    volumes:
      - .:/dd-authentification-api
    ports:
      - 5002:80

  box:
    image: busybox
    tty: true
    volumes:
      - bundle_cache:/bundle_cache

  redis:
    image: 'redis:4.0-alpine'
    # command: redis-server --requirepass akileebox
    command: redis-server
    ports:
      - 63800:6380
    volumes:
    - redis:/dd-authentification-api


