version: '3.2'
volumes:
  postgres_data: {}
  bundle_cache: {}
  app-gems:
  redis: {}

services:
  prod_app:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    # command: ./docker/script/bundle-install.sh
    # entrypoint: ./docker-entrypoint.sh
      args:
        - env=production
        - bundle_opts=--without development test
    depends_on:
      - prod_box
      - prod_redis
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
    ports:
      - 5002:3000
      - 5001:5000

    env_file:
     - ./.env_prod
    environment:
      - BUNDLE_PATH=/bundle_cache
      - REDIS_URL=redis://redis:6379/0/cache
      # - RAILS_SECRET_KEYS=


  prod_box:
    image: busybox
    tty: true
    volumes:
      - bundle_cache:/bundle_cache

  prod_redis:
    image: 'redis:4.0-alpine'
    # command: redis-server --requirepass akileebox
    command: redis-server
    # env_file:
    #   - ./.env
    # ports:
    #   - 6379:6379
    volumes:
      - redis:/app

  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - /var/lib/postgresql/pgdata:/var/lib/postgresql/pgdata
    ports:
      - 5032:5432