version: '3.2'
volumes:
  postgres_data: {}
  bundle_cache: {}
  app-gems:
  redis: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/prod.Dockerfile

    # command: ./docker/script/bundle-install.sh
    command: ./docker/script/bundle-install.sh
    entrypoint: ./docker-entrypoint.sh
    depends_on:
      - db
      - box
      - redis
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
    ports:
      - 3001:3000
    env_file:
     - ./.env

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/prod.Dockerfile
    command: bundle exec sidekiq
    entrypoint: ./docker-entrypoint.sh
    depends_on:
      - db
      - box
      - redis
      - app
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
    env_file:
     - ./.env


  db:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 25432:5432
#  web:
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile
#    depends_on:
#      - app
#    volumes:
#      - .:/app
#    ports:
#      - 80:80
#      - 443:443

  box:
    image: busybox
    tty: true
    volumes:
      - bundle_cache:/bundle_cache

  redis:
    image: 'redis:4.0-alpine'
    # command: redis-server --requirepass akileebox
    command: redis-server
    ports:
      - 63801:6379
    volumes:
    - redis:/app


